name: App Template CI

on:
  workflow_dispatch:
    inputs:
        # Each major version has a release branch. By default we use the latest stable
        majorVersion:
          description: 'Which major version to release'
          required: false
          default: 'v6.x'
          type: choice
          options:
          - v6.x
          - v7.x

jobs:
  #############################################
  # Tests First baby! We fail, no build :(
  #############################################
  tests:
    uses: ./.github/workflows/tests.yml

  #############################################
  # Build & Publish
  #############################################
  build:
    name: Build & Publish
    needs: tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_TOKEN }}

      # - name: Tag Version
      #   uses: rickstaa/action-create-tag@v1.6.1
      #   with:
      #     tag: "latest"
      #     tag_exists_error: false
      #     message: "Latest release"

      # - name: Publish To ForgeBox
      #   run: |
      #     box forgebox publish --force
