# Publish Github Release
name: Github Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: taiki-e/create-gh-release-action@v1.6.2
        with:
          changelog: changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
