# Publish Github Release
name: Github Release

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: taiki-e/create-gh-release-action@v1.6.1
        with:
          changelog: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
