name: ForgeBox Release

on:
  workflow_dispatch:
    inputs:
       doTests:
          description: 'Run Tests Before release'
          required: false
          default: false
          type: boolean
       versionType:
          description: 'Bump Version'
          required: false
          default: 'minor'
          type: choice
          options:
          - minor
          - patch

jobs:
  #############################################
  # Tests First baby! We fail, no build :(
  #############################################
  tests:
    if: ${{ inputs.doTests }}
    uses: ./.github/workflows/tests.yml

  #############################################
  # Build & Publish
  #############################################
  build:
    name: Build & Publish
    needs: tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_TOKEN }}

      - name: Get Latest Version
        run: |
          echo "VERSION=`cat box.json | jq '.version' -r`" >> $GITHUB_ENV

      - name: Tag Version
        uses: rickstaa/action-create-tag@v1.6.1
        with:
          tag: "${{ env.VERSION }}"
          tag_exists_error: false
          message: "Latest Release"

      - name: Publish To ForgeBox & Bump to next release
        run: |
          box forgebox publish --force
          box bump --${{ inputs.versionType }} noTagVersion

      - name: Commit Version Bump
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: Github Actions
          author_email: info@ortussolutions.com
          message: 'Version bump'
